### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by josark2005** [JackMcKew/pyinstaller-action-windows#1]
```python
Installing collected packages: urllib3, pywin32, pyperclip, system-hotkey, playsound
    Running setup.py install for pyperclip: started
    Running setup.py install for pyperclip: finished with status 'done'
Successfully installed playsound-1.2.2 pyperclip-1.8.0 pywin32-228 system-hotkey-1.0.3 urllib3-1.25.9
WARNING: You are using pip version 19.3.1; however, version 20.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
192 INFO: PyInstaller: 3.6
192 INFO: Python: 3.7.5
193 INFO: Platform: Windows-7-6.1.7601-SP1
205 INFO: UPX is not available.
205 INFO: Removing temporary files and cleaning cache in C:\users\root\Application Data\pyinstaller
Traceback (most recent call last):
  File "c:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\Python37\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\Python37\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\Python37\lib\site-packages\PyInstaller\building\build_main.py", line 734, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\Python37\lib\site-packages\PyInstaller\building\build_main.py", line 636, in build
    os.makedirs(pth)
  File "c:\Python37\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] Invalid name: '/tmp\\*'
```

**Comment by JackMcKew** [comment]
Hi there!

Thank you for raising an issue.

This error occurs when the path is correctly set (the default is `src`). Ensure to specify a path to where your `.py`, `spec` and/or `requirements.txt` reside as a relative path from the root.

I've set up a complete working example repository over at: <https://github.com/JackMcKew/pyinstaller-action-windows-example> and updated the README to answer this question for others <https://github.com/JackMcKew/pyinstaller-action-windows#faq>.

Please let me know if you still have problems!
