### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'hooksconfig'

### ISSUE THREAD

**Issue by iamjing66** [JackMcKew/pyinstaller-action-windows#16]
```shell
180 INFO: PyInstaller: 3.6
180 INFO: Python: 3.7.5
181 INFO: Platform: Windows-7-6.1.7601-SP1
192 INFO: UPX is not available.
192 INFO: Removing temporary files and cleaning cache in C:\users\root\Application Data\pyinstaller
Traceback (most recent call last):
  File "c:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\Python37\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\Python37\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\Python37\lib\site-packages\PyInstaller\building\build_main.py", line 734, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\Python37\lib\site-packages\PyInstaller\building\build_main.py", line 681, in build
    exec(code, spec_namespace)
  File "login.spec", line 19, in <module>
    noarchive=False)
TypeError: __init__() got an unexpected keyword argument 'hooksconfig'
```
when I use this action in my project, this error info show each time, and the action will not go on.
please help

**Comment by renanstn** [comment]
I"m having the same problem here :(

**Comment by renanstn** [comment]
I"m having the same problem here

To avoid this error, I just remove the `hooksconfig={},` from `.spec` file

**Comment by iamjing66** [comment]
> I"m having the same problem here
> 
> To avoid this error, I just remove the `hooksconfig={},` from `.spec` file

thanks for your solution,maybe I will try another way
