### ISSUE TITLE
PermissionError: [Errno 13] Permission denied - Z: Github Workspace

### ISSUE THREAD

**Issue by frederick0291** [JackMcKew/pyinstaller-action-windows#32]
I am getting this error:

```Traceback (most recent call last):
  File "c:\Python37\lib\runpy.py", line [193](https://github.com/REPH-PEO/HTML_CONVERTER/actions/runs/3467506047/jobs/5792437889#step:4:194), in _run_module_as_main
    "__main__", mod_spec)
  File "c:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\Python37\lib\site-packages\PyInstaller\__main__.py", line 179, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\Python37\lib\site-packages\PyInstaller\__main__.py", line 60, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\Python37\lib\site-packages\PyInstaller\building\build_main.py", line 963, in main
    build(specfile, distpath, workpath, clean_build)
  File "c:\Python37\lib\site-packages\PyInstaller\building\build_main.py", line 885, in build
    exec(code, spec_namespace)
  File "html-converter.spec", line 20, in <module>
    noarchive=False,
  File "c:\Python37\lib\site-packages\PyInstaller\building\build_main.py", line 410, in __init__
    self.__postinit__()
  File "c:\Python37\lib\site-packages\PyInstaller\building\datastruct.py", line 173, in __postinit__
    self.assemble()
  File "c:\Python37\lib\site-packages\PyInstaller\building\build_main.py", line 573, in assemble
    priority_scripts.append(self.graph.add_script(script))
  File "c:\Python37\lib\site-packages\PyInstaller\depend\analysis.py", line 268, in add_script
    self._top_script_node = super().add_script(pathname)
  File "c:\Python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1415, in add_script
    with open(pathname, 'rb') as fp:
PermissionError: [Errno 13] Permission denied: 'Z:\\github\\workspace\\src'

**Comment by JackMcKew** [comment]
This looks like the path you are using in your script is referencing a drive on your machine?

**Comment by JackMcKew** [comment]
Can you please provide a reproducible example?
