### ISSUE TITLE
Unexpected optimize

### ISSUE THREAD

**Issue by zamkorus** [JackMcKew/pyinstaller-action-windows#50]
Hello my runs ends with this error:
1874 INFO: PyInstaller: 5.13.0
1874 INFO: Python: 3.10.1
1944 INFO: Platform: Windows-10-10.0.18362
1959 INFO: Removing temporary files and cleaning cache in C:\users\root\AppData\Local\pyinstaller
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line [86](https://github.com/PlohnenSoftware/familiada_ZSP/actions/runs/8788836453/job/24117206694#step:4:87), in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\Python310\lib\site-packages\PyInstaller\__main__.py", line 194, in _console_script_run
    run()
  File "C:\Python310\lib\site-packages\PyInstaller\__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Python310\lib\site-packages\PyInstaller\__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 1019, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Python310\lib\site-packages\PyInstaller\building\build_main.py", line [94](https://github.com/PlohnenSoftware/familiada_ZSP/actions/runs/8788836453/job/24117206694#step:4:95)4, in build
    exec(code, spec_namespace)
  File "main.spec", line 4, in <module>
    a = Analysis(
TypeError: Analysis.__init__() got an unexpected keyword argument 'optimize'

**Comment by zamkorus** [comment]
After doing [this](https://github.com/PlohnenSoftware/familiada_ZSP/commit/764a0154c99bb693739c5452b0ac1f8364a41621) it works
